---
title: "Correlation and linear regression"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
set.seed(12546)

x1 <- rnorm(500, 15, 2) - 10
y1 <- 5*x1 + 54 + rnorm(500, 0, 6)
lm.xy <- lm(y1 ~ x1)
```

Correlation Coefficient
===================

Input {.sidebar}
-------------------

In this example we can dynamically choose a value of Pearson's correlation coefficient between two variables, and see the scatterplot between them. 

```{r}
sliderInput("r", label = "Correlation coefficient",
              min = -1, max = 1, value = 0, step = 0.05)
```


Stupac
---------------------

### Scatterplot

```{r}
renderPlot({
  x <- rnorm(500, 0, 1)
  y <- input$r*input$r*sign(input$r)*x + (1 - input$r*input$r)*rnorm(500, 0, 1)
  x <- 2*x + 20
  y <- 3*y + 90
  plot(x, y,
       xlab = "x",
       ylab = "y",
       main = paste("Scatterplot\nr = ", format(input$r, digits=3), sep=""),
       pch = 16, col = "blue",
       xlim = c(14, 26), ylim = c(80, 100), las = 1
  )
  pom <- lm(y~x)
  abline(pom, lwd=2, col = "red")
})
```

The Least Squares
=========================

Input {.sidebar data-width=300}
-------------------

In linear regression we estimate values of regression coefficients by minimizing the sum of squares of residuals. Try to find the regression coefficients in this example manually by sliding the input slides to minimize the sum of squares.

```{r}

inputPanel(
  sliderInput("b1", label = "Regression coefficient", 
               min = -5, max = 15, value = 10, step = 0.1),
  
  sliderInput("b0", label = "Regression constant",
               min = 50, max = 60, value = 50, step = 0.1)
  )
```

Stupac {data-width=700}
---------------------

### Scatterplot with the Chosen Line

```{r}
renderPlot({
   plot(x1, y1,
        xlab = "x",
        ylab = "y",
        main = paste("b0 = ", format(input$b0, digits=3), 
                     ", b1 = ", format(input$b1, digits=3), sep=""),
        pch = 16, col = "blue",
        xlim = c(0, 12), ylim = c(35, 120), 
        las = 1
   )
   abline(a=input$b0, b=input$b1, lwd=2, col = "red")
   pom <- sum((y1 - input$b0 - input$b1 * x1)**2)
   text(10, 40, paste("Sum of squared residuals: ", format(pom, digits = 3)))
})
```

One more example
========================================

```{r}
renderPlot({
   plot(x1, y1,
        xlab = "x",
        ylab = "y",
        main = paste("b0 = ", format(coefficients(lm.xy)[1], digits=3), 
                     ", b1 = ", format(coefficients(lm.xy)[2], digits=3), sep=""),
        pch = 16, col = "blue",
        xlim = c(0, 12), ylim = c(35, 120), 
        las = 1
   )
   abline(lm.xy, lwd=2, col = "red")
   text(10, 40, paste("Sum of squared residuals: ",
                      format(sum(residuals(lm.xy)^2), digits = 3)))
})
summary(lm.xy)
```





